### ISSUE TITLE
tempest ImportError on ussuri/candidate 

### ISSUE THREAD

**Issue by samuelallan72** [canonical/snap-tempest#194]
```
$ sudo snap install tempest --channel ussuri/candidate
$ tempest run

=========================
Failures during discovery
=========================
--- import errors ---
Failed to call load_tests:
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/loader.py", line 130, in loadTestsFromModule
    return load_tests(self, tests, pattern)
  File "/snap/tempest/417/lib/python3.8/site-packages/tempest/test_discover/test_discover.py", line 34, in load_tests
    suite.addTests(loader.discover(full_test_dir, pattern=pattern,
  File "/usr/lib/python3.8/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib/python3.8/unittest/loader.py", line 414, in _find_tests
    yield from self._find_tests(full_path, pattern, namespace)
  File "/usr/lib/python3.8/unittest/loader.py", line 414, in _find_tests
    yield from self._find_tests(full_path, pattern, namespace)
  File "/usr/lib/python3.8/unittest/loader.py", line 405, in _find_tests
    tests, should_recurse = self._find_test_path(
  File "/usr/lib/python3.8/unittest/loader.py", line 458, in _find_test_path
    raise ImportError(
ImportError: 'test_agents' module incorrectly imported from '/snap/tempest/553/lib/python3.8/site-packages/tempest/api/compute/admin'. Expected '/snap/tempest/417/lib/python3.8/site-packages/tempest/api/compute/admin'. Is this module globally installed?

================================================================================
The above traceback was encountered during test discovery which imports all the found test modules in the specified test_path.
```

**Comment by samuelallan72** [comment]
I think this was related to running tempest against a tempest workspace created by tempest from a different snap revision.
