### ISSUE TITLE
tempest run --smoke fails on ImportError

### ISSUE THREAD

**Issue by marosg42** [canonical/snap-tempest#52]
snap channel `2023.1/stable`
`installed:            34.1.0            (106) 96MB`

```
tempest run --smoke

=========================
Failures during discovery
=========================
--- import errors ---
Failed to call load_tests:
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/loader.py", line 130, in loadTestsFromModule
    return load_tests(self, tests, pattern)
  File "/snap/tempest/25/lib/python3.10/site-packages/tempest/test_discover/test_discover.py", line 34, in load_tests
    suite.addTests(loader.discover(full_test_dir, pattern=pattern,
  File "/usr/lib/python3.10/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib/python3.10/unittest/loader.py", line 414, in _find_tests
    yield from self._find_tests(full_path, pattern, namespace)
  File "/usr/lib/python3.10/unittest/loader.py", line 414, in _find_tests
    yield from self._find_tests(full_path, pattern, namespace)
  File "/usr/lib/python3.10/unittest/loader.py", line 405, in _find_tests
    tests, should_recurse = self._find_test_path(
  File "/usr/lib/python3.10/unittest/loader.py", line 458, in _find_test_path
    raise ImportError(
ImportError: 'test_agents' module incorrectly imported from '/snap/tempest/106/lib/python3.10/site-packages/tempest/api/compute/admin'. Expected '/snap/tempest/25/lib/python3.10/site-packages/tempest/api/compute/admin'. Is this module globally installed?

================================================================================
The above traceback was encountered during test discovery which imports all the found test modules in the specified test_path.
```

**Comment by agileshaw** [comment]
This seems to be the same as reported in #8 , which is a limitation of the upstream tempest: each workspace contain the path of the tempest instance that initialized it, and an ImportError will be produced if the path does match with what you are actually running (e.g. after refreshing tempest).

We will see if it is possible to work around this limitation with some additional implementations in the snap project. For the moment, if you are running mismatch tempest/workspace, you need to either:
- initialize a new workspace, or 
- change the path in `.stestr.conf` of an existing workspace.

Closing this issues as a duplicate. Feel free to reopen if needed.
