### ISSUE TITLE
Congress and Murano plugins seem to be missing dependencies (Ussuri channel)

### ISSUE THREAD

**Issue by aieri** [canonical/snap-tempest#53]
If I try running smoke tests against an ussuri cloud, I ran into missing python modules for the Congress and Murano plugins (although I have no such services and those tests should not even run).

Here is an extract from the CLI output:

```
Failed to import test module: murano_tempest_tests.tests.scenario.application_catalog.test_security_groups
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/snap/tempest/118/lib/python3.8/site-packages/murano_tempest_tests/tests/scenario/application_catalog/test_security_groups.py", line 20, in <module>
    from murano_tempest_tests.tests.scenario.application_catalog import base
  File "/snap/tempest/118/lib/python3.8/site-packages/murano_tempest_tests/tests/scenario/application_catalog/base.py", line 25, in <module>
    from tempest.services import orchestration
ModuleNotFoundError: No module named 'tempest.services'
```

```
Failed to import test module: congress_tempest_plugin.tests.scenario.test_congress_z3
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/snap/tempest/118/lib/python3.8/site-packages/congress_tempest_plugin/tests/scenario/test_congress_z3.py", line 23, in <module>
    from congress_tempest_plugin.tests.scenario import manager_congress
  File "/snap/tempest/118/lib/python3.8/site-packages/congress_tempest_plugin/tests/scenario/manager_congress.py", line 29, in <module>
    from tempest import manager as tempestmanager
ImportError: cannot import name 'manager' from 'tempest' (/snap/tempest/118/lib/python3.8/site-packages/tempest/__init__.py)
```

It's always those two modules that seem to be missing.

**Comment by aieri** [comment]
This would be "fixed" via #159
