### ISSUE TITLE
discovery tool does not work with sunbeam

### ISSUE THREAD

**Issue by marosg42** [canonical/snap-tempest#57]
As pointed by @javacruft it looks like the discovery tool cannot deal with path based suffixes as used in sunbeam for service endpoints.

```
2023-10-26 11:44:53.694 3162729 INFO tempest.lib.common.rest_client [ req-d7dc3006-3034-4f73-801c-00138df2fdb7 ] Request (main): 201 POST http://10.20.21.13/openstack-keystone/v3/auth/tokens
 0.510s                                                                                                                                                                                       
2023-10-26 11:44:53.961 3162729 INFO tempest.lib.common.rest_client [ req-4f418628-b795-40fb-a571-e5bb2dac6ec2 ] Request (main): 200 GET http://10.20.21.13/openstack-keystone/v3/projects 0.2
65s                                                                                                                                                                                           
2023-10-26 11:44:54.240 3162729 INFO tempest.lib.common.rest_client [ req-443de4e8-5cd3-4aab-8c87-f127cc1c70ec ] Request (main): 200 GET http://10.20.21.13/openstack-keystone/v3/services 0.2
75s                                                                                                                                                                                           
2023-10-26 11:44:54.965 3162729 CRITICAL tempest [-] Unhandled error: config_tempest.services.base.ServiceError: Request on service 'compute' with url 'http://10.20.21.13:80/' failed with co
de 404                                                                                                                                                                                        
2023-10-26 11:44:54.965 3162729 ERROR tempest Traceback (most recent call last):                                                                                                              
2023-10-26 11:44:54.965 3162729 ERROR tempest   File "/snap/tempest/126/bin/discover-tempest-config", line 10, in <module>
2023-10-26 11:44:54.965 3162729 ERROR tempest     sys.exit(main())                                                                                                                            
2023-10-26 11:44:54.965 3162729 ERROR tempest   File "/snap/tempest/126/lib/python3.10/site-packages/config_tempest/main.py", line 597, in main
2023-10-26 11:44:54.965 3162729 ERROR tempest     config_tempest(
2023-10-26 11:44:54.965 3162729 ERROR tempest   File "/snap/tempest/126/lib/python3.10/site-packages/config_tempest/main.py", line 539, in config_tempest
2023-10-26 11:44:54.965 3162729 ERROR tempest     services = Services(clients, conf, credentials)
2023-10-26 11:44:54.965 3162729 ERROR tempest   File "/snap/tempest/126/lib/python3.10/site-packages/config_tempest/services/services.py", line 42, in __init__
2023-10-26 11:44:54.965 3162729 ERROR tempest     self.discover()
2023-10-26 11:44:54.965 3162729 ERROR tempest   File "/snap/tempest/126/lib/python3.10/site-packages/config_tempest/services/services.py", line 118, in discover
2023-10-26 11:44:54.965 3162729 ERROR tempest     service.set_versions()
2023-10-26 11:44:54.965 3162729 ERROR tempest   File "/snap/tempest/126/lib/python3.10/site-packages/config_tempest/services/compute.py", line 27, in set_versions
2023-10-26 11:44:54.965 3162729 ERROR tempest     body = self.do_get(url, top_level=top_level)
2023-10-26 11:44:54.965 3162729 ERROR tempest   File "/snap/tempest/126/lib/python3.10/site-packages/config_tempest/services/base.py", line 76, in do_get
2023-10-26 11:44:54.965 3162729 ERROR tempest     raise ServiceError("Request on service '%s' with url '%s' failed"
2023-10-26 11:44:54.965 3162729 ERROR tempest config_tempest.services.base.ServiceError: Request on service 'compute' with url 'http://10.20.21.13:80/' failed with code 404
```

**Comment by chanchiwai-ray** [comment]
This issue should be fixed by https://review.opendev.org/c/openinfra/python-tempestconf/+/902124. But we will need to wait the new release of `python-tempestconf`, and update the `snapcraft.yaml`

**Comment by chanchiwai-ray** [comment]
Fix is released on the stable channel of the snap
